/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as NotReadyRouteImport } from './routes/not-ready'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as MissionsProject_slugRouteImport } from './routes/missions/$project_slug'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminNewUserRouteImport } from './routes/admin/new-user'
import { Route as AdminNewTeamRouteImport } from './routes/admin/new-team'
import { Route as AdminNewRoleRouteImport } from './routes/admin/new-role'
import { Route as AdminNewProjectRouteImport } from './routes/admin/new-project'
import { Route as TeamSubteamsTeam_slugRouteImport } from './routes/team/subteams/$team_slug'
import { Route as TeamPeopleUser_slugRouteImport } from './routes/team/people/$user_slug'
import { Route as MissionsEditProject_slugRouteImport } from './routes/missions/edit/$project_slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as TeamSubteamsEditTeam_slugRouteImport } from './routes/team/subteams/edit/$team_slug'
import { Route as MissionsRolesEditRole_slugRouteImport } from './routes/missions/roles/edit/$role_slug'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const NotReadyRoute = NotReadyRouteImport.update({
  id: '/not-ready',
  path: '/not-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsProject_slugRoute = MissionsProject_slugRouteImport.update({
  id: '/missions/$project_slug',
  path: '/missions/$project_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewUserRoute = AdminNewUserRouteImport.update({
  id: '/admin/new-user',
  path: '/admin/new-user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewTeamRoute = AdminNewTeamRouteImport.update({
  id: '/admin/new-team',
  path: '/admin/new-team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewRoleRoute = AdminNewRoleRouteImport.update({
  id: '/admin/new-role',
  path: '/admin/new-role',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewProjectRoute = AdminNewProjectRouteImport.update({
  id: '/admin/new-project',
  path: '/admin/new-project',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSubteamsTeam_slugRoute = TeamSubteamsTeam_slugRouteImport.update({
  id: '/team/subteams/$team_slug',
  path: '/team/subteams/$team_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamPeopleUser_slugRoute = TeamPeopleUser_slugRouteImport.update({
  id: '/team/people/$user_slug',
  path: '/team/people/$user_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsEditProject_slugRoute =
  MissionsEditProject_slugRouteImport.update({
    id: '/missions/edit/$project_slug',
    path: '/missions/edit/$project_slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSubteamsEditTeam_slugRoute =
  TeamSubteamsEditTeam_slugRouteImport.update({
    id: '/team/subteams/edit/$team_slug',
    path: '/team/subteams/edit/$team_slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const MissionsRolesEditRole_slugRoute =
  MissionsRolesEditRole_slugRouteImport.update({
    id: '/missions/roles/edit/$role_slug',
    path: '/missions/roles/edit/$role_slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/new-project': typeof AdminNewProjectRoute
  '/admin/new-role': typeof AdminNewRoleRoute
  '/admin/new-team': typeof AdminNewTeamRoute
  '/admin/new-user': typeof AdminNewUserRoute
  '/admin/users': typeof AdminUsersRoute
  '/missions/$project_slug': typeof MissionsProject_slugRoute
  '/team/': typeof TeamIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/missions/edit/$project_slug': typeof MissionsEditProject_slugRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
  '/team/subteams/$team_slug': typeof TeamSubteamsTeam_slugRoute
  '/missions/roles/edit/$role_slug': typeof MissionsRolesEditRole_slugRoute
  '/team/subteams/edit/$team_slug': typeof TeamSubteamsEditTeam_slugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/new-project': typeof AdminNewProjectRoute
  '/admin/new-role': typeof AdminNewRoleRoute
  '/admin/new-team': typeof AdminNewTeamRoute
  '/admin/new-user': typeof AdminNewUserRoute
  '/admin/users': typeof AdminUsersRoute
  '/missions/$project_slug': typeof MissionsProject_slugRoute
  '/team': typeof TeamIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/missions/edit/$project_slug': typeof MissionsEditProject_slugRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
  '/team/subteams/$team_slug': typeof TeamSubteamsTeam_slugRoute
  '/missions/roles/edit/$role_slug': typeof MissionsRolesEditRole_slugRoute
  '/team/subteams/edit/$team_slug': typeof TeamSubteamsEditTeam_slugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/admin/new-project': typeof AdminNewProjectRoute
  '/admin/new-role': typeof AdminNewRoleRoute
  '/admin/new-team': typeof AdminNewTeamRoute
  '/admin/new-user': typeof AdminNewUserRoute
  '/admin/users': typeof AdminUsersRoute
  '/missions/$project_slug': typeof MissionsProject_slugRoute
  '/team/': typeof TeamIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/missions/edit/$project_slug': typeof MissionsEditProject_slugRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
  '/team/subteams/$team_slug': typeof TeamSubteamsTeam_slugRoute
  '/missions/roles/edit/$role_slug': typeof MissionsRolesEditRole_slugRoute
  '/team/subteams/edit/$team_slug': typeof TeamSubteamsEditTeam_slugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/sign-in'
    | '/sign-up'
    | '/admin/new-project'
    | '/admin/new-role'
    | '/admin/new-team'
    | '/admin/new-user'
    | '/admin/users'
    | '/missions/$project_slug'
    | '/team/'
    | '/api/auth/$'
    | '/missions/edit/$project_slug'
    | '/team/people/$user_slug'
    | '/team/subteams/$team_slug'
    | '/missions/roles/edit/$role_slug'
    | '/team/subteams/edit/$team_slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/sign-in'
    | '/sign-up'
    | '/admin/new-project'
    | '/admin/new-role'
    | '/admin/new-team'
    | '/admin/new-user'
    | '/admin/users'
    | '/missions/$project_slug'
    | '/team'
    | '/api/auth/$'
    | '/missions/edit/$project_slug'
    | '/team/people/$user_slug'
    | '/team/subteams/$team_slug'
    | '/missions/roles/edit/$role_slug'
    | '/team/subteams/edit/$team_slug'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/sign-in'
    | '/sign-up'
    | '/admin/new-project'
    | '/admin/new-role'
    | '/admin/new-team'
    | '/admin/new-user'
    | '/admin/users'
    | '/missions/$project_slug'
    | '/team/'
    | '/api/auth/$'
    | '/missions/edit/$project_slug'
    | '/team/people/$user_slug'
    | '/team/subteams/$team_slug'
    | '/missions/roles/edit/$role_slug'
    | '/team/subteams/edit/$team_slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  ErrorRoute: typeof ErrorRoute
  NotReadyRoute: typeof NotReadyRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  AdminNewProjectRoute: typeof AdminNewProjectRoute
  AdminNewRoleRoute: typeof AdminNewRoleRoute
  AdminNewTeamRoute: typeof AdminNewTeamRoute
  AdminNewUserRoute: typeof AdminNewUserRoute
  AdminUsersRoute: typeof AdminUsersRoute
  MissionsProject_slugRoute: typeof MissionsProject_slugRoute
  TeamIndexRoute: typeof TeamIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MissionsEditProject_slugRoute: typeof MissionsEditProject_slugRoute
  TeamPeopleUser_slugRoute: typeof TeamPeopleUser_slugRoute
  TeamSubteamsTeam_slugRoute: typeof TeamSubteamsTeam_slugRoute
  MissionsRolesEditRole_slugRoute: typeof MissionsRolesEditRole_slugRoute
  TeamSubteamsEditTeam_slugRoute: typeof TeamSubteamsEditTeam_slugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-ready': {
      id: '/not-ready'
      path: '/not-ready'
      fullPath: '/not-ready'
      preLoaderRoute: typeof NotReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/$project_slug': {
      id: '/missions/$project_slug'
      path: '/missions/$project_slug'
      fullPath: '/missions/$project_slug'
      preLoaderRoute: typeof MissionsProject_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-user': {
      id: '/admin/new-user'
      path: '/admin/new-user'
      fullPath: '/admin/new-user'
      preLoaderRoute: typeof AdminNewUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-team': {
      id: '/admin/new-team'
      path: '/admin/new-team'
      fullPath: '/admin/new-team'
      preLoaderRoute: typeof AdminNewTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-role': {
      id: '/admin/new-role'
      path: '/admin/new-role'
      fullPath: '/admin/new-role'
      preLoaderRoute: typeof AdminNewRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/new-project': {
      id: '/admin/new-project'
      path: '/admin/new-project'
      fullPath: '/admin/new-project'
      preLoaderRoute: typeof AdminNewProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/subteams/$team_slug': {
      id: '/team/subteams/$team_slug'
      path: '/team/subteams/$team_slug'
      fullPath: '/team/subteams/$team_slug'
      preLoaderRoute: typeof TeamSubteamsTeam_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/people/$user_slug': {
      id: '/team/people/$user_slug'
      path: '/team/people/$user_slug'
      fullPath: '/team/people/$user_slug'
      preLoaderRoute: typeof TeamPeopleUser_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/edit/$project_slug': {
      id: '/missions/edit/$project_slug'
      path: '/missions/edit/$project_slug'
      fullPath: '/missions/edit/$project_slug'
      preLoaderRoute: typeof MissionsEditProject_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/subteams/edit/$team_slug': {
      id: '/team/subteams/edit/$team_slug'
      path: '/team/subteams/edit/$team_slug'
      fullPath: '/team/subteams/edit/$team_slug'
      preLoaderRoute: typeof TeamSubteamsEditTeam_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/roles/edit/$role_slug': {
      id: '/missions/roles/edit/$role_slug'
      path: '/missions/roles/edit/$role_slug'
      fullPath: '/missions/roles/edit/$role_slug'
      preLoaderRoute: typeof MissionsRolesEditRole_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  ErrorRoute: ErrorRoute,
  NotReadyRoute: NotReadyRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  AdminNewProjectRoute: AdminNewProjectRoute,
  AdminNewRoleRoute: AdminNewRoleRoute,
  AdminNewTeamRoute: AdminNewTeamRoute,
  AdminNewUserRoute: AdminNewUserRoute,
  AdminUsersRoute: AdminUsersRoute,
  MissionsProject_slugRoute: MissionsProject_slugRoute,
  TeamIndexRoute: TeamIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MissionsEditProject_slugRoute: MissionsEditProject_slugRoute,
  TeamPeopleUser_slugRoute: TeamPeopleUser_slugRoute,
  TeamSubteamsTeam_slugRoute: TeamSubteamsTeam_slugRoute,
  MissionsRolesEditRole_slugRoute: MissionsRolesEditRole_slugRoute,
  TeamSubteamsEditTeam_slugRoute: TeamSubteamsEditTeam_slugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
