/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotReadyRouteImport } from './routes/not-ready'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as TeamPeopleUser_slugRouteImport } from './routes/team/people/$user_slug'

const NotReadyRoute = NotReadyRouteImport.update({
  id: '/not-ready',
  path: '/not-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamPeopleUser_slugRoute = TeamPeopleUser_slugRouteImport.update({
  id: '/team/people/$user_slug',
  path: '/team/people/$user_slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/team': typeof TeamIndexRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/team': typeof TeamIndexRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/team/': typeof TeamIndexRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/team'
    | '/team/people/$user_slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/team'
    | '/team/people/$user_slug'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/team/'
    | '/team/people/$user_slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  ErrorRoute: typeof ErrorRoute
  NotReadyRoute: typeof NotReadyRoute
  TeamIndexRoute: typeof TeamIndexRoute
  TeamPeopleUser_slugRoute: typeof TeamPeopleUser_slugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-ready': {
      id: '/not-ready'
      path: '/not-ready'
      fullPath: '/not-ready'
      preLoaderRoute: typeof NotReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/people/$user_slug': {
      id: '/team/people/$user_slug'
      path: '/team/people/$user_slug'
      fullPath: '/team/people/$user_slug'
      preLoaderRoute: typeof TeamPeopleUser_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  ErrorRoute: ErrorRoute,
  NotReadyRoute: NotReadyRoute,
  TeamIndexRoute: TeamIndexRoute,
  TeamPeopleUser_slugRoute: TeamPeopleUser_slugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
