/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as SpaceRouteImport } from './routes/space'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as NotReadyRouteImport } from './routes/not-ready'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as R9njdxq3eRouteImport } from './routes/9njdxq3e'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as NewslettersIndexRouteImport } from './routes/newsletters/index'
import { Route as DisciplinesIndexRouteImport } from './routes/disciplines/index'
import { Route as ProjectsProject_slugRouteImport } from './routes/projects/$project_slug'
import { Route as NewslettersSlugRouteImport } from './routes/newsletters/$slug'
import { Route as DisciplinesDiscipline_slugRouteImport } from './routes/disciplines/$discipline_slug'
import { Route as ApiTicketSignupRouteImport } from './routes/api/ticket-signup'
import { Route as TeamPeopleUser_slugRouteImport } from './routes/team/people/$user_slug'

const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const SpaceRoute = SpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const NotReadyRoute = NotReadyRouteImport.update({
  id: '/not-ready',
  path: '/not-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const R9njdxq3eRoute = R9njdxq3eRouteImport.update({
  id: '/9njdxq3e',
  path: '/9njdxq3e',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersIndexRoute = NewslettersIndexRouteImport.update({
  id: '/newsletters/',
  path: '/newsletters/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesIndexRoute = DisciplinesIndexRouteImport.update({
  id: '/disciplines/',
  path: '/disciplines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProject_slugRoute = ProjectsProject_slugRouteImport.update({
  id: '/projects/$project_slug',
  path: '/projects/$project_slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewslettersSlugRoute = NewslettersSlugRouteImport.update({
  id: '/newsletters/$slug',
  path: '/newsletters/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplinesDiscipline_slugRoute =
  DisciplinesDiscipline_slugRouteImport.update({
    id: '/disciplines/$discipline_slug',
    path: '/disciplines/$discipline_slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTicketSignupRoute = ApiTicketSignupRouteImport.update({
  id: '/api/ticket-signup',
  path: '/api/ticket-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamPeopleUser_slugRoute = TeamPeopleUser_slugRouteImport.update({
  id: '/team/people/$user_slug',
  path: '/team/people/$user_slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/9njdxq3e': typeof R9njdxq3eRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/roadmap': typeof RoadmapRoute
  '/shop': typeof ShopRoute
  '/space': typeof SpaceRoute
  '/sponsors': typeof SponsorsRoute
  '/api/ticket-signup': typeof ApiTicketSignupRoute
  '/disciplines/$discipline_slug': typeof DisciplinesDiscipline_slugRoute
  '/newsletters/$slug': typeof NewslettersSlugRoute
  '/projects/$project_slug': typeof ProjectsProject_slugRoute
  '/disciplines': typeof DisciplinesIndexRoute
  '/newsletters': typeof NewslettersIndexRoute
  '/team': typeof TeamIndexRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/9njdxq3e': typeof R9njdxq3eRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/roadmap': typeof RoadmapRoute
  '/shop': typeof ShopRoute
  '/space': typeof SpaceRoute
  '/sponsors': typeof SponsorsRoute
  '/api/ticket-signup': typeof ApiTicketSignupRoute
  '/disciplines/$discipline_slug': typeof DisciplinesDiscipline_slugRoute
  '/newsletters/$slug': typeof NewslettersSlugRoute
  '/projects/$project_slug': typeof ProjectsProject_slugRoute
  '/disciplines': typeof DisciplinesIndexRoute
  '/newsletters': typeof NewslettersIndexRoute
  '/team': typeof TeamIndexRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/9njdxq3e': typeof R9njdxq3eRoute
  '/apply': typeof ApplyRoute
  '/contact': typeof ContactRoute
  '/error': typeof ErrorRoute
  '/not-ready': typeof NotReadyRoute
  '/roadmap': typeof RoadmapRoute
  '/shop': typeof ShopRoute
  '/space': typeof SpaceRoute
  '/sponsors': typeof SponsorsRoute
  '/api/ticket-signup': typeof ApiTicketSignupRoute
  '/disciplines/$discipline_slug': typeof DisciplinesDiscipline_slugRoute
  '/newsletters/$slug': typeof NewslettersSlugRoute
  '/projects/$project_slug': typeof ProjectsProject_slugRoute
  '/disciplines/': typeof DisciplinesIndexRoute
  '/newsletters/': typeof NewslettersIndexRoute
  '/team/': typeof TeamIndexRoute
  '/team/people/$user_slug': typeof TeamPeopleUser_slugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/9njdxq3e'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/roadmap'
    | '/shop'
    | '/space'
    | '/sponsors'
    | '/api/ticket-signup'
    | '/disciplines/$discipline_slug'
    | '/newsletters/$slug'
    | '/projects/$project_slug'
    | '/disciplines'
    | '/newsletters'
    | '/team'
    | '/team/people/$user_slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/9njdxq3e'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/roadmap'
    | '/shop'
    | '/space'
    | '/sponsors'
    | '/api/ticket-signup'
    | '/disciplines/$discipline_slug'
    | '/newsletters/$slug'
    | '/projects/$project_slug'
    | '/disciplines'
    | '/newsletters'
    | '/team'
    | '/team/people/$user_slug'
  id:
    | '__root__'
    | '/'
    | '/9njdxq3e'
    | '/apply'
    | '/contact'
    | '/error'
    | '/not-ready'
    | '/roadmap'
    | '/shop'
    | '/space'
    | '/sponsors'
    | '/api/ticket-signup'
    | '/disciplines/$discipline_slug'
    | '/newsletters/$slug'
    | '/projects/$project_slug'
    | '/disciplines/'
    | '/newsletters/'
    | '/team/'
    | '/team/people/$user_slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R9njdxq3eRoute: typeof R9njdxq3eRoute
  ApplyRoute: typeof ApplyRoute
  ContactRoute: typeof ContactRoute
  ErrorRoute: typeof ErrorRoute
  NotReadyRoute: typeof NotReadyRoute
  RoadmapRoute: typeof RoadmapRoute
  ShopRoute: typeof ShopRoute
  SpaceRoute: typeof SpaceRoute
  SponsorsRoute: typeof SponsorsRoute
  ApiTicketSignupRoute: typeof ApiTicketSignupRoute
  DisciplinesDiscipline_slugRoute: typeof DisciplinesDiscipline_slugRoute
  NewslettersSlugRoute: typeof NewslettersSlugRoute
  ProjectsProject_slugRoute: typeof ProjectsProject_slugRoute
  DisciplinesIndexRoute: typeof DisciplinesIndexRoute
  NewslettersIndexRoute: typeof NewslettersIndexRoute
  TeamIndexRoute: typeof TeamIndexRoute
  TeamPeopleUser_slugRoute: typeof TeamPeopleUser_slugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/space': {
      id: '/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof SpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-ready': {
      id: '/not-ready'
      path: '/not-ready'
      fullPath: '/not-ready'
      preLoaderRoute: typeof NotReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/9njdxq3e': {
      id: '/9njdxq3e'
      path: '/9njdxq3e'
      fullPath: '/9njdxq3e'
      preLoaderRoute: typeof R9njdxq3eRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/': {
      id: '/newsletters/'
      path: '/newsletters'
      fullPath: '/newsletters'
      preLoaderRoute: typeof NewslettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/': {
      id: '/disciplines/'
      path: '/disciplines'
      fullPath: '/disciplines'
      preLoaderRoute: typeof DisciplinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project_slug': {
      id: '/projects/$project_slug'
      path: '/projects/$project_slug'
      fullPath: '/projects/$project_slug'
      preLoaderRoute: typeof ProjectsProject_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletters/$slug': {
      id: '/newsletters/$slug'
      path: '/newsletters/$slug'
      fullPath: '/newsletters/$slug'
      preLoaderRoute: typeof NewslettersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disciplines/$discipline_slug': {
      id: '/disciplines/$discipline_slug'
      path: '/disciplines/$discipline_slug'
      fullPath: '/disciplines/$discipline_slug'
      preLoaderRoute: typeof DisciplinesDiscipline_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ticket-signup': {
      id: '/api/ticket-signup'
      path: '/api/ticket-signup'
      fullPath: '/api/ticket-signup'
      preLoaderRoute: typeof ApiTicketSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/people/$user_slug': {
      id: '/team/people/$user_slug'
      path: '/team/people/$user_slug'
      fullPath: '/team/people/$user_slug'
      preLoaderRoute: typeof TeamPeopleUser_slugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R9njdxq3eRoute: R9njdxq3eRoute,
  ApplyRoute: ApplyRoute,
  ContactRoute: ContactRoute,
  ErrorRoute: ErrorRoute,
  NotReadyRoute: NotReadyRoute,
  RoadmapRoute: RoadmapRoute,
  ShopRoute: ShopRoute,
  SpaceRoute: SpaceRoute,
  SponsorsRoute: SponsorsRoute,
  ApiTicketSignupRoute: ApiTicketSignupRoute,
  DisciplinesDiscipline_slugRoute: DisciplinesDiscipline_slugRoute,
  NewslettersSlugRoute: NewslettersSlugRoute,
  ProjectsProject_slugRoute: ProjectsProject_slugRoute,
  DisciplinesIndexRoute: DisciplinesIndexRoute,
  NewslettersIndexRoute: NewslettersIndexRoute,
  TeamIndexRoute: TeamIndexRoute,
  TeamPeopleUser_slugRoute: TeamPeopleUser_slugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
